[project]
name = "wkagent"
version = "0.1.0"
description = "Japanese Kanji Learning Assistant"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.31.0",
    "openai-agents",
    "requests>=2.32.3",
]
